github.com:
    users:
        am225723:
            oauth_token: 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
    git_protocol: https
    user: am225723
    oauth_token: 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
