github.com:
    users:
        am225723:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: am225723
